---
apiVersion: v1
kind: Service
metadata:
  annotations:
    jkube.io/git-branch: master
    jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/spring-boot-docker
    jkube.io/git-url: https://github.com/chandanbsc/spring-boot-docker.git
    jkube.io/scm-tag: HEAD
    api.service.kubernetes.io/path: /
    jkube.io/git-commit: 8ca6bea457057df524420a73a7d7dad1b38c766e
  labels:
    expose: "true"
    testProject: spring-boot-yaml-label-all
    app: spring-boot-docker
    provider: jkube
    version: 0.1.1-SNAPSHOT
    group: com.example
  name: spring-boot-docker
spec:
  ports:
  - nodePort: 32200
    port: 8080
  selector:
    app: spring-boot-docker
    provider: jkube
    group: com.example
  type: NodePort
